### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Twikii** [Quatrecentquatre-404/BetterDiscord-MessageBluring#1]
Hello,

When i add it to my plugin folder, he doesnt start, need to be updated ?

**Comment by Quatrecentquatre-404** [comment]
Hi,
It only blurs messages when you are streaming or screen sharing. Else, there is no changes with the default Discord's behaviour.

**Comment by Twikii** [comment]
Yes but it doesnt load the plugin

**Comment by Twikii** [comment]
Check my screenshot: https://twikii.be/upload/JDGD6xcHjy.png

**Comment by Twikii** [comment]
C'est régler en privé, tout va parfaitement.
Merci pour le plugin!

**Comment by Quatrecentquatre-404** [comment]
Make sure you downloaded the code :
- from the raw past : https://raw.githubusercontent.com/Quatrecentquatre-404/BetterDiscord-MessageBluring/main/MessageBluring.plugin.js
- from the "download code" green button and then drag and drop the plugin file from the zip file into the plugin folder.
