### ISSUE TITLE
Extraneous console log

### ISSUE THREAD

**Issue by rauenzi** [Quatrecentquatre-404/BetterDiscord-MessageBluring#2]
Accidentally left a console.log in https://github.com/Quatrecentquatre-404/BetterDiscord-MessageBluring/blob/b92ce9e3cf570ca93ba17782f652037909e65aa3/MessageBluring.plugin.js#L77

Please resubmit to BD when removed. 

p.s. it should be `Blurring` with 2 `r`s

**Comment by Quatrecentquatre-404** [comment]
> Accidentally left a console.log in https://github.com/Quatrecentquatre-404/BetterDiscord-MessageBluring/blob/b92ce9e3cf570ca93ba17782f652037909e65aa3/MessageBluring.plugin.js#L77
> 
> 
> 
> Please resubmit to BD when removed. 
> 
> 
> 
> p.s. it should be `Blurring` with 2 `r`s

Alright, thanks for the advice and your time.
